### ISSUE TITLE
index page without dropdown button is throw the error

### ISSUE THREAD

**Issue by cuongtqtran** [trueberryless-org/starlight-sidebar-topics-dropdown#1]
Hi mate,

index page without dropdown button is throwing the error

![image](https://github.com/user-attachments/assets/2e948402-b1f9-43a2-a0bc-b757faa25b73)

BTW, your plugin is awesome!

If some have showcase section, you can add my site [my site](https://docs.ghostfam.com/) for site showcase.

**Comment by cuongtqtran** [comment]
The plugin is is breaking index page (home) and mobile menu and even language switch.

**Comment by trueberryless** [comment]
Oh, thank you very much for noticing this mistake. I'll probably have to adjust the script to run only, when the component is displayed. Like make the script locally...

Another good idea of you is a showcase site, I'll add that soon!

**Comment by trueberryless** [comment]
Okay, new version is published, can you update the plugin to `v0.2.1` and try the following things for me:

- index error should be gone (I checked that)
- mobile menu should work (I didn't check that...)
- language switch should work (I didn't check that...)

**Comment by trueberryless** [comment]
Oh, and I almost forgot: Thanks for the appreciation but the credit goes to @HiDeoo, who originally created the plugin: [starlight-sidebar-topics](https://starlight-sidebar-topics.netlify.app/).

**Comment by cuongtqtran** [comment]
> Oh, and I almost forgot: Thanks for the appreciation but the credit goes to @HiDeoo, who originally created the plugin: [starlight-sidebar-topics](https://starlight-sidebar-topics.netlify.app/).

The issue has been resolved. Thank you for your hard work, @trueberryless and @HiDeoo. Much respect for your efforts!
