### ISSUE TITLE
Possibility to hide main dropdown if link and directory are the same, or it has empty/no-label

### ISSUE THREAD

**Issue by opluan** [trueberryless-org/starlight-sidebar-topics-dropdown#4]
Hi again, is there a way to simply build an entire directory without a label dropdown? I really only need the separation of two topics "lectures" and "projects", but projects itself isn't intended to have multiple sub-pages, only itself.

```
{
  label: 'Projetos',
  link: '/projects/',
  icon: 'information',
  items: [{label: "Todos", autogenerate: { directory: 'projects' }}],
}
```

![image](https://github.com/user-attachments/assets/7e2ec435-f09f-40cc-8f70-71194d5bb61b)
```
{
  label: 'Projetos',
  link: '/projects/',
  icon: 'information',
  items: [{label: "", autogenerate: { directory: 'projects' }}],
}
```
![image](https://github.com/user-attachments/assets/518427a7-347c-4fa3-a526-03d57b2585ca)

**Comment by trueberryless** [comment]
This is an issue which bugs myself. I unfortunately think that this is a limitation of Starlight itself, I'll talk to the maintainers, why they chose to make this limitation and maybe create a discussion / issue in their repo...

**Comment by trueberryless** [comment]
Reference to Discord Thread: https://discord.com/channels/830184174198718474/1312909867262021683

**Comment by trueberryless** [comment]
I have currently a repro which applies some custom CSS: https://github.com/trueberryless/starlight-flat-sidebar

However, I'm considering implementing this into this plugin because it is a good idea, thank you very much!
